package LanguageDateTime.behavior;

/*Generated by MPS */

import java.time.LocalDateTime;
import org.jetbrains.mps.openapi.model.SNode;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class DateTimeInstant_BehaviorDescriptor extends Instant_BehaviorDescriptor {
  public LocalDateTime virtual_getDateTime_6963719656193938358(SNode __thisNode__) {
    return null;
  }
  public LocalDate virtual_getDate_7775955438098512649(SNode __thisNode__) {
    return null;
  }
  public LocalTime virtual_getTime_7775955438098512671(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "LanguageDateTime.structure.DateTimeInstant";
  }

}
