package LanguageDateTime.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.EditorComponent;
import jetbrains.mps.openapi.editor.update.UpdaterListener;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class Days_Behavior {
  public static void call_SetEditorContext_8794515008209942547(SNode __thisNode__, EditorComponent editorcomponent) {
    Days__BehaviorDescriptor.SetEditorContext_id7CcpcRWcvwj(__thisNode__, editorcomponent);
  }
  public static UpdaterListener call_createListener_8794515008209972274(SNode __thisNode__, final EditorComponent editorComponent) {
    return Days__BehaviorDescriptor.createListener_id7CcpcRWcAKM(__thisNode__, editorComponent);
  }
  public static void call_elementchanged_7152909203783017668(SNode __thisNode__, EditorComponent editorComponent) {
    Days__BehaviorDescriptor.elementchanged_id6d4fgnE6Yj4(__thisNode__, editorComponent);
  }
  public static void call_removelistener_7152909203783020107(SNode __thisNode__, EditorComponent editorComponent) {
    Days__BehaviorDescriptor.removelistener_id6d4fgnE6YTb(__thisNode__, editorComponent);
  }
  public static void call_grabtext_7152909203783020497(SNode __thisNode__, EditorComponent editorComponent) {
    Days__BehaviorDescriptor.grabtext_id6d4fgnE6YZh(__thisNode__, editorComponent);
  }
}
