package LanguageDateTime.behavior;

/*Generated by MPS */


/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class isSameAs_BehaviorDescriptor extends DateTimeOperator_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "LanguageDateTime.structure.isSameAs";
  }

}
