package CopyTextPlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;

public class CopyTextPlugin_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("CopyTextPlugin");
  public CopyTextPlugin_ApplicationPlugin() {
  }
  public PluginId getId() {
    return myId;
  }
  public void createGroups() {
    // actions w/o parameters 
    addAction(new CopyAsText_Action());
    // groups 
  }
}
