package LanguageDateTime.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.textGen.SNodeTextGen;

public abstract class ConvertIntegerToString {
  public static void intValue(int i, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(ConvertIntegerToString.ConvertToString(i, ctx));
  }
  public static void intValue(int i, SNodeTextGen ctx) {
    // method left for compile-time compatibility for generated textgen code (MPS 3.2). 
    // MPS compiles modules on start-up. If client keeps generated source code AND if an old TextGen  
    // references utility operations of MPS-supplied TextGen, existing sources won't compile without 
    // this method present. 
  }
  protected static String ConvertToString(int i, final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    Integer temp;
    temp = i;
    return temp.toString();
  }
}
