package LanguageDateTime.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.Arrays;
import jetbrains.mps.text.rt.TextGenModelOutline;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final long[] myId2Index;
  public TextGenAspectDescriptor() {
    myId2Index = new long[6];
    myId2Index[0] = 0x6b28562f90495b4L;
    myId2Index[1] = 0x6b28562f9055584L;
    myId2Index[2] = 0x6b28562f90555dbL;
    myId2Index[3] = 0x6b28562f90555f6L;
    myId2Index[4] = 0x6b28562f905561bL;
    myId2Index[5] = 0x6b28562f905569fL;
  }
  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SConceptId id) {
    final int index = Arrays.binarySearch(myId2Index, id.getIdValue());
    switch (index) {
      case 0:
        return new DateTimeInterval_TextGen();
      case 1:
        return new Years_TextGen();
      case 2:
        return new Months_TextGen();
      case 3:
        return new Days_TextGen();
      case 4:
        return new Date_TextGen();
      case 5:
        return new Time_TextGen();
      default:
        return null;
    }
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
  }
}
