package TestLanguageDateTime.plugin;

/*Generated by MPS */

import com.mbeddr.mpsutil.interpreter.rt.InterpreterBase;
import java.util.List;
import com.mbeddr.mpsutil.interpreter.rt.IEvaluator;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import com.mbeddr.mpsutil.interpreter.rt.ConceptEvaluatorBase;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import com.mbeddr.mpsutil.interpreter.rt.IContext;
import LanguageDateTime.behavior.Instant__BehaviorDescriptor;
import com.mbeddr.mpsutil.interpreter.rt.InterpreterRuntimeException;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import com.mbeddr.mpsutil.interpreter.rt.ITypeMapper;
import com.mbeddr.mpsutil.interpreter.rt.IRelationship;

public class InterpreterDateTimeInterpreter extends InterpreterBase {
  public InterpreterDateTimeInterpreter() {
    init();
  }

  protected void populateEvaluators(List<? extends IEvaluator> evaluators) {
    ListSequence.fromList(((List<IEvaluator>) evaluators)).addElement(new ConceptEvaluatorBase(MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905561bL, "LanguageDateTime.structure.Date"), true) {
      public Object evaluateEvaluator(SNode node, IContext context) {
        try {
          return Instant__BehaviorDescriptor.getDateTime_id62$6y76Q5eQ.invoke(node);
        } catch (RuntimeException ex) {
          throw new InterpreterRuntimeException("Date()", node, ex);
        }
      }

      @Override
      public String toString() {
        return "Date";
      }
    });
    ListSequence.fromList(((List<IEvaluator>) evaluators)).addElement(new ConceptEvaluatorBase(MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f906954dL, "LanguageDateTime.structure.isAfter"), true) {
      public Object evaluateEvaluator(SNode node, IContext context) {
        try {
          {
            final SNode n1 = SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1"));
            if (SNodeOperations.isInstanceOf(n1, MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905561bL, "LanguageDateTime.structure.Date"))) {
              LocalDate d1 = Instant__BehaviorDescriptor.getDate_id6JDJ$mH8fG9.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1")));
              LocalDate d2 = Instant__BehaviorDescriptor.getDate_id6JDJ$mH8fG9.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f9069551L, "instant2")));
              return d1.isAfter(d2);
            }
          }
          {
            final SNode n2 = SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1"));
            if (SNodeOperations.isInstanceOf(n2, MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9058c50L, "LanguageDateTime.structure.DateTimeInstant"))) {
              LocalDateTime d3 = Instant__BehaviorDescriptor.getDateTime_id62$6y76Q5eQ.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1")));
              LocalDateTime d4 = Instant__BehaviorDescriptor.getDateTime_id62$6y76Q5eQ.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f9069551L, "instant2")));
              return d3.isAfter(d4);
            }
          }
          {
            final SNode n3 = SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1"));
            if (SNodeOperations.isInstanceOf(n3, MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905569fL, "LanguageDateTime.structure.Time"))) {
              LocalTime d5 = Instant__BehaviorDescriptor.getTime_id6JDJ$mH8fGv.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1")));
              LocalTime d6 = Instant__BehaviorDescriptor.getTime_id6JDJ$mH8fGv.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f9069551L, "instant2")));
              return d5.isAfter(d6);
            }
          }
          return false;
        } catch (RuntimeException ex) {
          throw new InterpreterRuntimeException("isAfter()", node, ex);
        }
      }

      @Override
      public String toString() {
        return "isAfter";
      }
    });
    ListSequence.fromList(((List<IEvaluator>) evaluators)).addElement(new ConceptEvaluatorBase(MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x5e765e444eab12ecL, "LanguageDateTime.structure.isBefore"), true) {
      public Object evaluateEvaluator(SNode node, IContext context) {
        try {
          {
            final SNode n1 = SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1"));
            if (SNodeOperations.isInstanceOf(n1, MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905561bL, "LanguageDateTime.structure.Date"))) {
              LocalDate d1 = Instant__BehaviorDescriptor.getDate_id6JDJ$mH8fG9.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1")));
              LocalDate d2 = Instant__BehaviorDescriptor.getDate_id6JDJ$mH8fG9.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f9069551L, "instant2")));
              return d1.isBefore(d2);
            }
          }
          {
            final SNode n2 = SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1"));
            if (SNodeOperations.isInstanceOf(n2, MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9058c50L, "LanguageDateTime.structure.DateTimeInstant"))) {
              LocalDateTime d3 = Instant__BehaviorDescriptor.getDateTime_id62$6y76Q5eQ.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1")));
              LocalDateTime d4 = Instant__BehaviorDescriptor.getDateTime_id62$6y76Q5eQ.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f9069551L, "instant2")));
              return d3.isBefore(d4);
            }
          }
          {
            final SNode n3 = SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1"));
            if (SNodeOperations.isInstanceOf(n3, MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905569fL, "LanguageDateTime.structure.Time"))) {
              LocalTime d5 = Instant__BehaviorDescriptor.getTime_id6JDJ$mH8fGv.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1")));
              LocalTime d6 = Instant__BehaviorDescriptor.getTime_id6JDJ$mH8fGv.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f9069551L, "instant2")));
              return d5.isBefore(d6);
            }
          }
          return false;
        } catch (RuntimeException ex) {
          throw new InterpreterRuntimeException("isBefore()", node, ex);
        }
      }

      @Override
      public String toString() {
        return "isBefore";
      }
    });
    ListSequence.fromList(((List<IEvaluator>) evaluators)).addElement(new ConceptEvaluatorBase(MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x5e765e444eab1d78L, "LanguageDateTime.structure.isSameAs"), true) {
      public Object evaluateEvaluator(SNode node, IContext context) {
        try {
          {
            final SNode n1 = SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1"));
            if (SNodeOperations.isInstanceOf(n1, MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905561bL, "LanguageDateTime.structure.Date"))) {
              LocalDate d1 = Instant__BehaviorDescriptor.getDate_id6JDJ$mH8fG9.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1")));
              LocalDate d2 = Instant__BehaviorDescriptor.getDate_id6JDJ$mH8fG9.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f9069551L, "instant2")));
              return d1.equals(d2);
            }
          }
          {
            final SNode n2 = SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1"));
            if (SNodeOperations.isInstanceOf(n2, MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9058c50L, "LanguageDateTime.structure.DateTimeInstant"))) {
              LocalDateTime d3 = Instant__BehaviorDescriptor.getDateTime_id62$6y76Q5eQ.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1")));
              LocalDateTime d4 = Instant__BehaviorDescriptor.getDateTime_id62$6y76Q5eQ.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f9069551L, "instant2")));
              return d3.equals(d4);
            }
          }
          {
            final SNode n3 = SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1"));
            if (SNodeOperations.isInstanceOf(n3, MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905569fL, "LanguageDateTime.structure.Time"))) {
              LocalTime d5 = Instant__BehaviorDescriptor.getTime_id6JDJ$mH8fGv.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f906954eL, "instant1")));
              LocalTime d6 = Instant__BehaviorDescriptor.getTime_id6JDJ$mH8fGv.invoke(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL, 0x6b28562f9069551L, "instant2")));
              return d5.equals(d6);
            }
          }
          return false;
        } catch (RuntimeException ex) {
          throw new InterpreterRuntimeException("isSameAs()", node, ex);
        }
      }

      @Override
      public String toString() {
        return "isSameAs";
      }
    });
    ListSequence.fromList(((List<IEvaluator>) evaluators)).addElement(new ConceptEvaluatorBase(MetaAdapterFactory.getConcept(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x10aecc076ca7b6e5L, "LanguageDateTime.structure.plusHours"), true) {
      public Object evaluateEvaluator(SNode node, IContext context) {
        try {
          return true;
        } catch (RuntimeException ex) {
          throw new InterpreterRuntimeException("plusHours()", node, ex);
        }
      }

      @Override
      public String toString() {
        return "plusHours";
      }
    });
  }


  protected void populateTypeMappers(List<? extends ITypeMapper> typeMappers) {
  }



  protected void populateRelationships(List<? extends IRelationship> relationships) {
  }
}
