package LanguageDateTime.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptDate = new ConceptDescriptorBuilder("LanguageDateTime.structure.Date", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905561bL)).super_("LanguageDateTime.structure.Instant").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495abL)).parents("LanguageDateTime.structure.Instant").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495abL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(482594770213230108L, "day"), new ConceptDescriptorBuilder.Prop(482594770213230110L, "month"), new ConceptDescriptorBuilder.Prop(482594770213230113L, "year")).properties("day", "month", "year").create();
  /*package*/ final ConceptDescriptor myConceptDateTimeInstant = new ConceptDescriptorBuilder("LanguageDateTime.structure.DateTimeInstant", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9058c50L)).super_("LanguageDateTime.structure.Instant").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495abL)).parents("LanguageDateTime.structure.Instant").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495abL)).childDescriptors(new ConceptDescriptorBuilder.Link(482594770213243985L, "date", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905561bL), false, false, false), new ConceptDescriptorBuilder.Link(482594770213243987L, "time", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905569fL), false, false, false)).children(new String[]{"date", "time"}, new boolean[]{false, false}).create();
  /*package*/ final ConceptDescriptor myConceptDateTimeInterval = new ConceptDescriptorBuilder("LanguageDateTime.structure.DateTimeInterval", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b4L)).super_("LanguageDateTime.structure.Interval").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495aaL)).parents("LanguageDateTime.structure.Interval").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495aaL)).create();
  /*package*/ final ConceptDescriptor myConceptDateTimeOperator = new ConceptDescriptorBuilder("LanguageDateTime.structure.DateTimeOperator", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).childDescriptors(new ConceptDescriptorBuilder.Link(482594770213311822L, "instant1", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495abL), false, false, false), new ConceptDescriptorBuilder.Link(482594770213311825L, "instant2", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495abL), false, false, false)).children(new String[]{"instant1", "instant2"}, new boolean[]{false, false}).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptDayOfWeek = new ConceptDescriptorBuilder("LanguageDateTime.structure.DayOfWeek", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).create();
  /*package*/ final ConceptDescriptor myConceptDays = new ConceptDescriptorBuilder("LanguageDateTime.structure.Days", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90555f6L)).super_("LanguageDateTime.structure.Duration").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9055583L)).parents("LanguageDateTime.structure.Duration").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9055583L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(482594770213230071L, "number")).properties("number").create();
  /*package*/ final ConceptDescriptor myConceptDuration = new ConceptDescriptorBuilder("LanguageDateTime.structure.Duration", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9055583L)).super_("LanguageDateTime.structure.TemporalEntity").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495acL)).parents("LanguageDateTime.structure.TemporalEntity").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495acL)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptFriday = new ConceptDescriptorBuilder("LanguageDateTime.structure.Friday", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905551fL)).super_("LanguageDateTime.structure.DayOfWeek").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).parents("LanguageDateTime.structure.DayOfWeek").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).create();
  /*package*/ final ConceptDescriptor myConceptInstant = new ConceptDescriptorBuilder("LanguageDateTime.structure.Instant", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495abL)).super_("LanguageDateTime.structure.TemporalEntity").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495acL)).parents("LanguageDateTime.structure.TemporalEntity").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495acL)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptInterval = new ConceptDescriptorBuilder("LanguageDateTime.structure.Interval", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495aaL)).super_("LanguageDateTime.structure.TemporalEntity").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495acL)).parents("LanguageDateTime.structure.TemporalEntity").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495acL)).childDescriptors(new ConceptDescriptorBuilder.Link(482594770213180845L, "hasBegin", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495abL), false, false, false), new ConceptDescriptorBuilder.Link(482594770213180847L, "hasEnd", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495abL), false, false, false)).children(new String[]{"hasBegin", "hasEnd"}, new boolean[]{false, false}).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptMonday = new ConceptDescriptorBuilder("LanguageDateTime.structure.Monday", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c8L)).super_("LanguageDateTime.structure.DayOfWeek").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).parents("LanguageDateTime.structure.DayOfWeek").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).create();
  /*package*/ final ConceptDescriptor myConceptMonths = new ConceptDescriptorBuilder("LanguageDateTime.structure.Months", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90555dbL)).super_("LanguageDateTime.structure.Duration").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9055583L)).parents("LanguageDateTime.structure.Duration").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9055583L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(482594770213230044L, "number")).properties("number").create();
  /*package*/ final ConceptDescriptor myConceptSaturday = new ConceptDescriptorBuilder("LanguageDateTime.structure.Saturday", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9055520L)).super_("LanguageDateTime.structure.DayOfWeek").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).parents("LanguageDateTime.structure.DayOfWeek").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).create();
  /*package*/ final ConceptDescriptor myConceptSunday = new ConceptDescriptorBuilder("LanguageDateTime.structure.Sunday", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c9L)).super_("LanguageDateTime.structure.DayOfWeek").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).parents("LanguageDateTime.structure.DayOfWeek").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).create();
  /*package*/ final ConceptDescriptor myConceptTemporalEntity = new ConceptDescriptorBuilder("LanguageDateTime.structure.TemporalEntity", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495acL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptTemporalUnit = new ConceptDescriptorBuilder("LanguageDateTime.structure.TemporalUnit", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).create();
  /*package*/ final ConceptDescriptor myConceptThursday = new ConceptDescriptorBuilder("LanguageDateTime.structure.Thursday", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905551eL)).super_("LanguageDateTime.structure.DayOfWeek").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).parents("LanguageDateTime.structure.DayOfWeek").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).create();
  /*package*/ final ConceptDescriptor myConceptTime = new ConceptDescriptorBuilder("LanguageDateTime.structure.Time", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905569fL)).super_("LanguageDateTime.structure.Instant").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495abL)).parents("LanguageDateTime.structure.Instant").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495abL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(482594770213230240L, "hours"), new ConceptDescriptorBuilder.Prop(482594770213230242L, "minutes"), new ConceptDescriptorBuilder.Prop(482594770213230245L, "seconds")).properties("hours", "minutes", "seconds").create();
  /*package*/ final ConceptDescriptor myConceptTuesday = new ConceptDescriptorBuilder("LanguageDateTime.structure.Tuesday", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495caL)).super_("LanguageDateTime.structure.DayOfWeek").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).parents("LanguageDateTime.structure.DayOfWeek").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).create();
  /*package*/ final ConceptDescriptor myConceptUnitDay = new ConceptDescriptorBuilder("LanguageDateTime.structure.UnitDay", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495baL)).super_("LanguageDateTime.structure.TemporalUnit").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).parents("LanguageDateTime.structure.TemporalUnit").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).create();
  /*package*/ final ConceptDescriptor myConceptUnitHour = new ConceptDescriptorBuilder("LanguageDateTime.structure.UnitHour", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495bbL)).super_("LanguageDateTime.structure.TemporalUnit").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).parents("LanguageDateTime.structure.TemporalUnit").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).create();
  /*package*/ final ConceptDescriptor myConceptUnitMinute = new ConceptDescriptorBuilder("LanguageDateTime.structure.UnitMinute", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495bcL)).super_("LanguageDateTime.structure.TemporalUnit").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).parents("LanguageDateTime.structure.TemporalUnit").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).create();
  /*package*/ final ConceptDescriptor myConceptUnitMonth = new ConceptDescriptorBuilder("LanguageDateTime.structure.UnitMonth", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b9L)).super_("LanguageDateTime.structure.TemporalUnit").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).parents("LanguageDateTime.structure.TemporalUnit").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).create();
  /*package*/ final ConceptDescriptor myConceptUnitSeconds = new ConceptDescriptorBuilder("LanguageDateTime.structure.UnitSeconds", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495bdL)).super_("LanguageDateTime.structure.TemporalUnit").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).parents("LanguageDateTime.structure.TemporalUnit").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).create();
  /*package*/ final ConceptDescriptor myConceptUnitYear = new ConceptDescriptorBuilder("LanguageDateTime.structure.UnitYear", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b6L)).super_("LanguageDateTime.structure.TemporalUnit").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).parents("LanguageDateTime.structure.TemporalUnit").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495b5L)).create();
  /*package*/ final ConceptDescriptor myConceptWednesday = new ConceptDescriptorBuilder("LanguageDateTime.structure.Wednesday", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f905551dL)).super_("LanguageDateTime.structure.DayOfWeek").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).parents("LanguageDateTime.structure.DayOfWeek").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495c7L)).create();
  /*package*/ final ConceptDescriptor myConceptYears = new ConceptDescriptorBuilder("LanguageDateTime.structure.Years", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9055584L)).super_("LanguageDateTime.structure.Duration").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9055583L)).parents("LanguageDateTime.structure.Duration").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9055583L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(482594770213229957L, "number")).properties("number").create();
  /*package*/ final ConceptDescriptor myConceptisAfter = new ConceptDescriptorBuilder("LanguageDateTime.structure.isAfter", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f906954dL)).super_("LanguageDateTime.structure.DateTimeOperator").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL)).parents("LanguageDateTime.structure.DateTimeOperator").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL)).create();
  /*package*/ final ConceptDescriptor myConceptisBefore = new ConceptDescriptorBuilder("LanguageDateTime.structure.isBefore", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x5e765e444eab12ecL)).super_("LanguageDateTime.structure.DateTimeOperator").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL)).parents("LanguageDateTime.structure.DateTimeOperator").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL)).create();
  /*package*/ final ConceptDescriptor myConceptisSameAs = new ConceptDescriptorBuilder("LanguageDateTime.structure.isSameAs", MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x5e765e444eab1d78L)).super_("LanguageDateTime.structure.DateTimeOperator").super_(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL)).parents("LanguageDateTime.structure.DateTimeOperator").parentIds(MetaIdFactory.conceptId(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x7b179a3374fa5a8eL)).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDate, myConceptDateTimeInstant, myConceptDateTimeInterval, myConceptDateTimeOperator, myConceptDayOfWeek, myConceptDays, myConceptDuration, myConceptFriday, myConceptInstant, myConceptInterval, myConceptMonday, myConceptMonths, myConceptSaturday, myConceptSunday, myConceptTemporalEntity, myConceptTemporalUnit, myConceptThursday, myConceptTime, myConceptTuesday, myConceptUnitDay, myConceptUnitHour, myConceptUnitMinute, myConceptUnitMonth, myConceptUnitSeconds, myConceptUnitYear, myConceptWednesday, myConceptYears, myConceptisAfter, myConceptisBefore, myConceptisSameAs);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0ib, conceptFqName)) {
      case 0:
        return myConceptDate;
      case 1:
        return myConceptDateTimeInstant;
      case 2:
        return myConceptDateTimeInterval;
      case 3:
        return myConceptDateTimeOperator;
      case 4:
        return myConceptDayOfWeek;
      case 5:
        return myConceptDays;
      case 6:
        return myConceptDuration;
      case 7:
        return myConceptFriday;
      case 8:
        return myConceptInstant;
      case 9:
        return myConceptInterval;
      case 10:
        return myConceptMonday;
      case 11:
        return myConceptMonths;
      case 12:
        return myConceptSaturday;
      case 13:
        return myConceptSunday;
      case 14:
        return myConceptTemporalEntity;
      case 15:
        return myConceptTemporalUnit;
      case 16:
        return myConceptThursday;
      case 17:
        return myConceptTime;
      case 18:
        return myConceptTuesday;
      case 19:
        return myConceptUnitDay;
      case 20:
        return myConceptUnitHour;
      case 21:
        return myConceptUnitMinute;
      case 22:
        return myConceptUnitMonth;
      case 23:
        return myConceptUnitSeconds;
      case 24:
        return myConceptUnitYear;
      case 25:
        return myConceptWednesday;
      case 26:
        return myConceptYears;
      case 27:
        return myConceptisAfter;
      case 28:
        return myConceptisBefore;
      case 29:
        return myConceptisSameAs;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0ib = new String[]{"LanguageDateTime.structure.Date", "LanguageDateTime.structure.DateTimeInstant", "LanguageDateTime.structure.DateTimeInterval", "LanguageDateTime.structure.DateTimeOperator", "LanguageDateTime.structure.DayOfWeek", "LanguageDateTime.structure.Days", "LanguageDateTime.structure.Duration", "LanguageDateTime.structure.Friday", "LanguageDateTime.structure.Instant", "LanguageDateTime.structure.Interval", "LanguageDateTime.structure.Monday", "LanguageDateTime.structure.Months", "LanguageDateTime.structure.Saturday", "LanguageDateTime.structure.Sunday", "LanguageDateTime.structure.TemporalEntity", "LanguageDateTime.structure.TemporalUnit", "LanguageDateTime.structure.Thursday", "LanguageDateTime.structure.Time", "LanguageDateTime.structure.Tuesday", "LanguageDateTime.structure.UnitDay", "LanguageDateTime.structure.UnitHour", "LanguageDateTime.structure.UnitMinute", "LanguageDateTime.structure.UnitMonth", "LanguageDateTime.structure.UnitSeconds", "LanguageDateTime.structure.UnitYear", "LanguageDateTime.structure.Wednesday", "LanguageDateTime.structure.Years", "LanguageDateTime.structure.isAfter", "LanguageDateTime.structure.isBefore", "LanguageDateTime.structure.isSameAs"};
}
