package LanguageDateTime.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class DateTimeInstant_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_xwg3dv_a(editorContext, node);
  }
  private EditorCell createCollection_xwg3dv_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_xwg3dv_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createRefNode_xwg3dv_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_xwg3dv_b0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_xwg3dv_c0(editorContext, node));
    return editorCell;
  }
  private EditorCell createRefNode_xwg3dv_a0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new DateTimeInstant_Editor.dateSingleRoleHandler_xwg3dv_a0(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9058c50L, 0x6b28562f9058c51L, "date"), editorContext);
    return provider.createCell();
  }
  private class dateSingleRoleHandler_xwg3dv_a0 extends SingleRoleCellProvider {
    public dateSingleRoleHandler_xwg3dv_a0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("date");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_date");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no date>";
    }
  }
  private EditorCell createConstant_xwg3dv_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, " ");
    editorCell.setCellId("Constant_xwg3dv_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_xwg3dv_c0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new DateTimeInstant_Editor.timeSingleRoleHandler_xwg3dv_c0(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f9058c50L, 0x6b28562f9058c53L, "time"), editorContext);
    return provider.createCell();
  }
  private class timeSingleRoleHandler_xwg3dv_c0 extends SingleRoleCellProvider {
    public timeSingleRoleHandler_xwg3dv_c0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("time");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_time");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no time>";
    }
  }
}
