package LanguageDateTime.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class DateTimeInterval_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_116npi_a(editorContext, node);
  }
  private EditorCell createCollection_116npi_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_116npi_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_116npi_a0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_116npi_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_116npi_c0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_116npi_d0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_116npi_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "from");
    editorCell.setCellId("Constant_116npi_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_116npi_b0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new DateTimeInterval_Editor.hasBeginSingleRoleHandler_116npi_b0(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495aaL, 0x6b28562f90495adL, "hasBegin"), editorContext);
    return provider.createCell();
  }
  private class hasBeginSingleRoleHandler_116npi_b0 extends SingleRoleCellProvider {
    public hasBeginSingleRoleHandler_116npi_b0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("hasBegin");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_hasBegin");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no hasBegin>";
    }
  }
  private EditorCell createConstant_116npi_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "until");
    editorCell.setCellId("Constant_116npi_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_116npi_d0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new DateTimeInterval_Editor.hasEndSingleRoleHandler_116npi_d0(node, MetaAdapterFactory.getContainmentLink(0xef5812095a6e41d4L, 0x8160c9506c67dfa5L, 0x6b28562f90495aaL, 0x6b28562f90495afL, "hasEnd"), editorContext);
    return provider.createCell();
  }
  private class hasEndSingleRoleHandler_116npi_d0 extends SingleRoleCellProvider {
    public hasEndSingleRoleHandler_116npi_d0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("hasEnd");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_hasEnd");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no hasEnd>";
    }
  }
}
