package TestLanguageDateTime.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x77c1272932b445a1L, 0xaaa405d08cec0b0eL, 0x7b179a3374fa6144L, "TestLanguageDateTime.structure.Rule"))) {
        return Collections.<ConceptEditor>singletonList(new Rule_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x77c1272932b445a1L, 0xaaa405d08cec0b0eL, 0x7b179a3374fa61beL, "TestLanguageDateTime.structure.TestContext"))) {
        return Collections.<ConceptEditor>singletonList(new TestContext_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
