package TestLanguageDateTime.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Context_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0x77c1272932b445a1L, 0xaaa405d08cec0b0eL, 0x6b28562f905fc07L, 0x6b28562f905fc08L, "entities"))) {
      tgs.appendNode(item);
    }
  }
  public String getFilename(SNode node) {
    return "/Users/diederikdulfer/context.txt";
  }
}
